version: '3'
networks:
    www: {  }
services:
    php_fpm: { container_name: laravocker_php_fpm, build: { context: ./php-fpm }, volumes: ['/home/diegoavelar/Projetos/smartcal/laravocker/.:/var/www/html'], networks: [www] }
    nginx: { container_name: laravocker_nginx, build: { context: ./nginx }, ports: ['8000:80'], volumes: ['/home/diegoavelar/Projetos/smartcal/laravocker/.:/usr/share/nginx/html'], networks: [www] }
    mysql: { build: { context: ./mysql }, container_name: laravocker_mysql, volumes: ['~/.laravocker/laravel/mysql:/var/lib/mysql'], environment: { MYSQL_ROOT_PASSWORD: laravocker, MYSQL_DATABASE: laravocker, MYSQL_USER: laravocker, MYSQL_PASSWORD: laravocker }, networks: [www] }
    redis: { container_name: laravocker_redis, build: { context: ./redis }, networks: [www] }
    cron: { container_name: laravocker_cron, build: { context: ./cron }, networks: [www] }
    horizon: { container_name: laravocker_horizon, build: { context: ./horizon }, volumes: ['/home/diegoavelar/Projetos/smartcal/laravocker/.:/var/www/html'], networks: [www] }
